accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views
from .forms import PasswordChangeCustomForm


app_name='account'
urlpatterns = [
    path("<int:id>/", views.dashboard, name="dashboard"),
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='contest:home'), name='logout'),
    path('confirm/<int:id>/', views.confirm, name='confirm'),
    path('resend-code/<int:id>/', views.resend_code, name='resend'),
    path('change-password/', auth_views.PasswordChangeView.as_view(form_class=PasswordChangeCustomForm,template_name='accounts/password_change.html', success_url=reverse_lazy('account:password_changed')), name='change_password'),
    path('change-password/done/', views.password_changed, name='password_changed'),
   
]

contests/urls.py
from django.urls import path

from . import views


app_name='contest'
urlpatterns = [
    path("", views.home, name="home"),
    path('verify/', views.verify, name='verify'),
    path('create_contest/', views.contest, name='create-contest'),
    path('join_contest/', views.join_contest, name='join-contest')
]

votenow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contests.urls')),
    path('account/', include('accounts.urls')),
]

contests/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _ 

from accounts.models import CustomUser

from .utils import generate_code

from datetime import datetime

# Create your models here.
class Contest(models.Model):
    name = models.CharField(_("name"), max_length=150, blank=False)
    description = models.TextField()
    organizer = models.ForeignKey(CustomUser, models.CASCADE)
    max_contestants = models.PositiveIntegerField()
    date = models.DateTimeField(default=datetime.now())
    contest_code = models.CharField(
        _("contest code"), max_length=12, default=generate_code
    )

    def __str__(self):
        return str(self.name)


class Contestant(models.Model):
    user = models.ForeignKey(CustomUser, models.CASCADE)
    contest = models.ForeignKey(Contest, models.CASCADE)
    name = models.CharField(_("name"), max_length=150, blank=False)
    manifesto = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.user.name) + ' ' + str(self.contest.name)

contests/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserCreationForm
from django.forms.widgets import PasswordInput, TextInput, EmailInput, FileInput, NumberInput
from .models import *

class UploadQrcodeForm(forms.Form):
    qrcode = forms.FileField()

class CreateContestForm(forms.ModelForm):
    name = forms.CharField(max_length=100, widget=TextInput(attrs={'class':'form-control', 'placeholder':'Enter title of Contest', 'required':'required'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Simple Description of contest', 'required':'required'}))
    max_contestants = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control', 'type':'number', 'placeholder':'Number of contestant in your contest', 'required':'required'}))

    class Meta:
        model = Contest
        fields = ['name', 'description', 'max_contestants']

class JoinContestForm(forms.Form):
    contest_code = forms.CharField(max_length=12, widget=TextInput(attrs={'class':'form-control', 'placeholder':'Contest Code', 'required':'required'}))
    manifesto = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Why should people vote you?', 'required':'required'}))

contests/views.py
from accounts.utils import decode_data
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UploadQrcodeForm, CreateContestForm, JoinContestForm
from .models import *

import cv2 as cv
import numpy as np
import os

def home(request):
    context = {}
    return render(request,'contests/index.html', context)

def verify(request):
    if request.method == 'POST':
        
        form = UploadQrcodeForm(request.POST, request.FILES)
        if form.is_valid():
            qrcode_str = request.FILES['qrcode'].read()
            npimg = np.fromstring(qrcode_str, np.uint8)
            im = cv.imdecode(npimg, cv.IMREAD_COLOR)
            det = cv.QRCodeDetector()
            retval, points, straight_qrcode = det.detectAndDecode(im)
            email = decode_data(retval)
            print(email)
            return redirect('contest:home')
    else:
        form = UploadQrcodeForm()
        context = {'form':form}
        return render(request, 'contests/verify.html', context)
        
@login_required
def contest(request):
    if request.method == 'POST':
        form= CreateContestForm(request.POST)
        if form.is_valid():
            contest = form.save(commit=False)
            contest.organizer = request.user
            contest.save()
            return redirect('account:dashboard', id=request.user.id)
    else:
        form = CreateContestForm()
        context = {'form':form}
        return render(request, 'contests/contest.html', context)

@login_required
def join_contest(request):
    if request.method == 'POST':
        form = JoinContestForm(request.POST)
        if form.is_valid():
            contest_code = form.cleaned_data['contest_code']
            manifesto = form.cleaned_data['manifesto']
            contest = Contest.objects.get(contest_code=contest_code)
            if contest:
                contestant = Contestant.objects.create(user=request.user,contest=contest, name=request.user.name, manifesto=manifesto)
                messages.success(request, 'Joined Contest sucessfully')
                return redirect('account:dashboard', id=request.user.id)
            else:
                context = {'form':form}
                messages.error(request, 'Contest does not exist')
                return render(request, 'contests/join.html', context)
    else:
        form = JoinContestForm()
        context = {'form':form}
        return render(request, 'contests/join.html', context)

templates/contests/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>VoteNow - {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block body %}
        {% if messages %}
            <div class='container'>
                {% for message in messages %}
                    <div class='notification {{message.tags}}' id='disappear'>
                        <p>{{message|safe}} <span class='float-right ' onclick='disappear()'><i class='fas fa-times'></i></span></p>      
                    </div>
                {% endfor %}
            </div>       
        {% endif %}
    {% endblock %}
    
  </body>
</html>
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

templates/contests/contest.html
{% extends 'accounts/base.html' %}
{% block title %} Create Event {% endblock %}

{% block body %}
    <div class="container" style="float: right; padding: 30px;">
        <div class="container">
            <form method ='POST'>
                {% csrf_token %}
                <div class="form-group">
                    {{forms.as_p}}
                </div>
                <button class="btn btn-info">Create Contest</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/contests/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>VoteNow - Voting Online Made Easy </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="#" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
        
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">VoteNow</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account:register' %}">Register</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact us</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">Welcome To VoteNow</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">We focus on usability, in order to supply voters with less technical experience with a usable scheme</p>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">What we Offer!</h2>
                        <hr class="divider light my-4" />
                        <p class="text-white-50 mb-4">In three 3 simple words <strong>Simplied Evoting System</strong></p>
                        <a class="btn btn-light btn-xl js-scroll-trigger" href="{% url 'account:register' %}">Get Started!</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">Let's Get In Touch!</h2>
                        <hr class="divider my-4" />
                        <p class="text-muted mb-5">Should you face any issues? Give us a call or send us an email and we will get back to you as soon as possible!</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fab fa-github-alt fa-3x mb-3 text-muted"></i>
                        <a class="d-block" href="https://github.com/Johnkayode/Votenow"> Repository</a>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                        <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                        <a class="d-block" href="mailto:contact@yourwebsite.com">contact@votenow.com</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - VoteNow</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/contests/join.html
{% extends 'accounts/base.html' %}
{% block title %}Join Contest{% endblock %}

{% block body %}
    <div class="container" style="float: right; padding: 30px;">
        <div class="container">
            <form method ='POST'>
                {% csrf_token %}
                <div class="form-group">
                    {{form.as_p}}
                </div>
                <button class="btn btn-info">Join Contest</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/contests/verify.html
<div class="container">
    <form method='post' enctype="multipart/form-data">
        {{form.qrcode}}
        {% csrf_token %}
        <input type='submit' value="Submit">
    </form>
</div>