accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views
from .forms import PasswordChangeCustomForm


app_name='account'
urlpatterns = [
    path("<int:id>/", views.dashboard, name="dashboard"),
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='contest:home'), name='logout'),
    path('confirm/<int:id>/', views.confirm, name='confirm'),
    path('resend-code/<int:id>/', views.resend_code, name='resend'),
    path('change-password/', auth_views.PasswordChangeView.as_view(form_class=PasswordChangeCustomForm,template_name='accounts/password_change.html', success_url=reverse_lazy('account:password_changed')), name='change_password'),
    path('change-password/done/', views.password_changed, name='password_changed'),
   
]

contests/urls.py
from django.urls import path

from . import views


app_name='contest'
urlpatterns = [
    path("", views.home, name="home"),
    path('verify/', views.verify, name='verify'),
    path('create_contest/', views.contest, name='create-contest'),
    path('join_contest/', views.join_contest, name='join-contest')
]

votenow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contests.urls')),
    path('account/', include('accounts.urls')),
]

accounts/models.py
import qrcode
from io import StringIO, BytesIO
import base64


from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.translation import gettext_lazy as _ 

from .utils import generate_code, encode_data


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_("email address cannot be left empty!"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True) 
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("superuser must set is_staff to True"))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("superuser must set is_superuser to True"))

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    first_name = None
    last_name = None
    email = models.EmailField(_("email address"), blank=False, unique=True)
    name = models.CharField(_("name"), max_length=150, blank=False)
    is_confirmed = models.BooleanField(_("is confirmed"), default=False)
    qr_code = models.ImageField(upload_to='qrcodes', blank=True, null=True)
    confirmation_code = models.IntegerField(
        _("confirmation code"), default=generate_code
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
 
    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def generate_qrcode(self):
        qr = qrcode.QRCode(version=1,error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=6, border=0)
        email = self.email
        data = encode_data(email)
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill='black', back_color='white')
        buffer = BytesIO()
        img.save(buffer, 'PNG')
        buffer.seek(0)
        filename = f'{self.name}'
        filebuffer = InMemoryUploadedFile(buffer,None, filename, 'image/png',buffer.getbuffer().nbytes, None)
        self.qr_code.save(filename, filebuffer)

contests/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _ 

from accounts.models import CustomUser

from .utils import generate_code

from datetime import datetime

# Create your models here.
class Contest(models.Model):
    name = models.CharField(_("name"), max_length=150, blank=False)
    description = models.TextField()
    organizer = models.ForeignKey(CustomUser, models.CASCADE)
    max_contestants = models.PositiveIntegerField()
    date = models.DateTimeField(default=datetime.now())
    contest_code = models.CharField(
        _("contest code"), max_length=12, default=generate_code
    )

    def __str__(self):
        return str(self.name)


class Contestant(models.Model):
    user = models.ForeignKey(CustomUser, models.CASCADE)
    contest = models.ForeignKey(Contest, models.CASCADE)
    name = models.CharField(_("name"), max_length=150, blank=False)
    manifesto = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.user.name) + ' ' + str(self.contest.name)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserCreationForm
from django.forms.widgets import PasswordInput, TextInput, EmailInput, FileInput, NumberInput
from .models import CustomUser


class CustomAuthForm(forms.Form):
    email = forms.CharField(widget=EmailInput(attrs={'class':'form-control', 'placeholder':'', 'required':'required'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class':'form-control','placeholder':'', 'required':'required'}))

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'', 'required':'required'}))
    password_ = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'', 'required':'required'}))

    class Meta:
        model = CustomUser
        fields = ('name','email') 
        widgets = {
        'name':TextInput(attrs={'class':'form-control', 'placeholder':'', 'required':'required'}),
        'email': EmailInput(attrs={'class':'form-control', 'placeholder':'', 'required':'required'}),
    }
    
class ConfirmationForm(forms.Form):
    confirmation_code = forms.CharField(widget=NumberInput(attrs={'class':'form-control','placeholder':'Confirmation Code ', 'required':'required'}))

class PasswordChangeCustomForm(PasswordChangeForm):
    old_password = forms.CharField(widget=PasswordInput(attrs={'class':'form-control', 'placeholder':'Password', 'required':'required'}))
    new_password1 = forms.CharField(widget=PasswordInput(attrs={'class':'form-control', 'placeholder':'New Password', 'required':'required'}))
    new_password2 = forms.CharField(widget=PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm New Password', 'required':'required'}))

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect

from .mail import send_confirm_mail
from .models import *
from .forms import CustomAuthForm, UserRegistrationForm, ConfirmationForm


@login_required
def dashboard(request, id):
    user = CustomUser.objects.filter(id=id).first()
    user_contests = user.contest_set.all()
    
    if user == request.user:
        context = {'user': user, 'contests':user_contests}
        return render(request, 'accounts/index.html', context)
    return redirect('contest:home')

    



def register(request):
    if request.user.is_authenticated:
        return redirect('account:dashboard', id=request.user.id)  

    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
       

        if user_form.is_valid():
            
            user = CustomUser.objects.filter(email=user_form.cleaned_data['email'])

            if user:
                context = {'user_form':user_form}
                messages.error(request, 'Email already exists')
                return render(request, 'accounts/register.html', context)

            else:
                new_user = user_form.save(commit=False)
                new_user.set_password(user_form.cleaned_data['password'])
                new_user.is_active = False
                new_user.save()
                new_user.generate_qrcode()
                '''
                try:
                    send_confirm_mail(user=new_user, email=user_form.cleaned_data['email'])
                    messages.info(request, 'A confirmation code has been sent to your address, please confirm your email address to activate your account')
                except:
                    messages.error(request, 'An error occured, try resending confirmation code')
                '''
                send_confirm_mail(user=new_user, email=user_form.cleaned_data['email'])
                messages.info(request, 'A confirmation code has been sent to your address, please confirm your email address to activate your account')
                return redirect('account:confirm', id=new_user.id)

        else:
            context = {'user_form':user_form}
            messages.error(request, 'An error occurred during registration.Try again')
            return render(request, 'accounts/register.html', context)
    else:
        user_form = UserRegistrationForm()
        context = {'user_form':user_form}
        return render(request, 'accounts/register.html', context)
    
def confirm(request, id):
    if request.method == 'POST':
        form = ConfirmationForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['confirmation_code']
            
            user = CustomUser.objects.filter(confirmation_code=code, id=id).first()
            if user is None:
                messages.error(request, 'Confirmation code is invalid')
                context = {'form':form}
                return render(request, 'accounts/confirm.html', context)
            elif user.is_confirmed or user.is_active:
                messages.info(request, 'Account already confirmed')
                return redirect('account:confirm',id=id)
            else:
                user.is_confirmed = True
                user.is_active = True
                user.save()
                messages.success(request, 'Your account has been confirmed. You can log in')
                return redirect('account:login')
        else:
            messages.error(request, 'An error occured during form submission')
            context = {'form':form, 'id':id}
            return render(request, 'accounts/confirm.html', context)


    form = ConfirmationForm()
    print(id)
    context = {'form':form, 'id':id}
    return render(request, 'accounts/confirm.html',context)

def resend_code(request, id):
    user = CustomUser.objects.get(id=id)
    form = ConfirmationForm()
    
    if user:
        send_confirm_mail(user=user, email=user.email)
        messages.info(request, 'A confirmation code has been sent to your address, please confirm your email address to activate your account')
        return redirect('account:confirm',id=id)

def password_changed(request):
    messages.success(request, 'Password changed')
    return redirect('account:dashboard')

def login_user(request):
    if request.user.is_authenticated:
        return redirect('account:dashboard', id=request.user.id)
    else:
        if request.method == 'POST':
            form = CustomAuthForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                user = authenticate(request, email = cd['email'], password=cd['password']) 
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        messages.success(request, 'Logged in successfully')
                        return redirect('account:dashboard', id=user.id)
                else:
                    messages.error(request, 'Account does not exist')
        form = CustomAuthForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)

templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>VoteNow - {% block title %}{% endblock %}</title>

    <link href="{% static 'css/account.css' %}" rel="stylesheet" />
    <!--Font Awesome-->
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
<body>
    {% if messages %}
    <div class=''>
        {% for message in messages %}
            <div class='notification {{message.tags}}' id='disappear'>
                <p>{{message|safe}} <span class='float-right ' onclick='disappear()'><i class='fas fa-times'></i></span></p>      
            </div>
        {% endfor %}
    </div>        
    {% endif %}

    <div class="wrapper">
        <div class="sidebar">
            <div class="logo">
                <img src="{{request.user.qr_code.url}}" alt="Qrcode" class="form-control">
                <p class="text">{{request.user.name}}</p>
            </div>

            <ul>
                <li><a href="{% url 'account:dashboard' id=request.user.id %}"><i class="fas fa-home"></i>Home</a></li>
                <li><a href="{% url 'contest:join-contest' %}"><i class="fas fa-project-diagram"></i>Join Contest</a></li>
                <li><a href="{% url 'contest:create-contest' %}"><i class="fas fa-poll-h"></i>Create Contest</a></li>
                <li><a href="{% url 'account:logout' %}"><i class="fas fa-sign-out-alt"></i>Logout</a></li>
            </ul>
            <!--
            <div class="social_media">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
        </div>
            -->
        </div>
    </div>
    {% block body %}{% endblock %}
</body>
</html>

templates/accounts/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VOTE NOW - Confirm Email</title>
</head>
<body>
    <div class="container">
        {% if messages %}
                    <div class=''>
                        {% for message in messages %}
                        <div class='notification {{message.tags}}' id='disappear'>
                                <p>{{message|safe}} <span class='float-right ' onclick='disappear()'><i class='fas fa-times'></i></span></p>
                                
                        </div>
                    </div>
                        {% endfor %}
                    
            {% endif %}
        <h1 class='reg-title'>Confirm Account</h1>
        <form method="POST">
            <!--Confirmation Code-->
            <div class="input-group">
                {{ form.confirmation_code }}
            </div>
           
            {% csrf_token %}
            <input type='submit' class='btn btn-block btn-success mb-4' value='Confirm'>
        </form>
        
        <a href='{% url "account:resend" id=id %}'>Resend Confirmation Code</a>
    </div>
</body>
</html>

templates/accounts/email.html
<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        
        <p style='font-size: 17px;'>
            Hi {{user.name}} 👋,<br>
        </p>   
        
        <p style='font-size: 17px; color: #222222;'>
            Welcome to VoteNow! <br>
           You're one step away from activating your account, your confirmation code is below:
           <br>
           <h2>{{user.confirmation_code}}</h2>
        </p>
        <hr style='color:grey'>
        
        <p>
            Best wishes,<br>
            The VoteNow Team.
        </p>
    </body>
</html>

templates/accounts/index.html
{%  extends 'accounts/base.html' %}

{% block title %}DashBoard{% endblock %}
{% block body %}
    <div class="main_content">
        <div class="header">My Profile</div>  
        <div class="info">
        <div class='row justify-content-center'>
            <div class="col-lg-12">
                <center>
                    <img src="{{user.qr_code.url}}" alt="Qrcode" class="mb-2" width='300px' height='300px'>
                    <br>
                    <a class='btn btn-primary btn-block' href='{{user.qr_code.url}}' download='{{user.name}}.jpg'>Download QRCode</a>
                    <p class='mt-1' style='font-size:12px'>Warning: Your QRcode is personal and should be secured.</p>
                    
                    <h3 class='mt-2'>{{user.name}}</h3>
                    <p>{{user.email}}</p>
                </center>
            </div>
        </div>
            <div class="container" style="float: right;">
                <h3>My Contests</h3>
                {% if not contests %}
                    <div style='background-color: #ffffff; padding:20px'>
                        <div><p class='text-muted text-small'>You haven't created any contest yet</p></div>
                    </div>
                {% else %}
                    {% for contest in contests %}
                        <div style='background-color: #ffffff; padding:20px'>
                            <div>
                                <p style='float:right'><i class='fas fa-poll'></i> 0 total votes</p>
                                <h4>{{contest.name}}</h4>
                                <p>{{contest.description}}</p>
                                Contest Code: {{contest.contest_code}}<br>
                                <h5 class='mt-2'>Contestants:</h5>
                                {% for contestant in contest.contestant_set.all %}
                                    <p>{{contestant.name}}<br><small>{{contestant.manifesto}}</small></p>
                                {% endfor %}
                                
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <h3>Joined Contests</h3>
                <div style='background-color: #ffffff; padding:20px'>
                    <div><p class="text-muted text-small">You haven't joined any contest yet</p></div>
                </div>
            </div>
        </div>
    </div>
{% endblock%}

templates/accounts/login.html
{% extends 'contests/base.html' %}
{% block title %} Login Now {% endblock %}

{% block body %}
    <div class="container">

        <div id="login">
            <div class="container">
                <div id="login-row" class="row justify-content-center align-items-center">
                    <div id="login-column" class="col-md-6">
                        <div id="login-box" class="col-md-12">
                            <form id="login-form" class="form" action="" method="post">
                                {% csrf_token %}
                                <h3 class="text-center text-info">Login</h3>
                                <div class="form-group">
                                    <label for="username" class="text-info">Email:</label><br>
                                    
                                        {{ form.email }}
                                    
                                </div>
                                <div class="form-group">
                                    <label for="password" class="text-info">Password:</label><br>
                        
                                        {{ form.password }}

                                </div>
                                <br />
                                <div class="form-group">
                                    <input type="submit" name="submit" class="btn btn-info btn-md" value="Sign In">
                                </div>
                                <div id="register-link" class="text-right">
                                    <p class="text-muted">Don't have an account? <a href="{% url 'account:register' %}" class="text-info">Register</a></p>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--STYLE SHEET STARTS HERE -->
    <style>
        body {
            margin: 0;
            padding: 0;
            background: url('https://cdn.pixabay.com/photo/2017/03/19/18/00/the-traffic-light-2157162_960_720.jpg');
            height: 100vh;
        }
        #login .container #login-row #login-column #login-box {
        margin-top: 120px;
        max-width: 500px;
        height: 320px;
        border: 1px solid #9C9C9C;
        background-color: #EAEAEA;
        }
        #login .container #login-row #login-column #login-box #login-form {
        padding: 20px;
        }
        #login .container #login-row #login-column #login-box #login-form #register-link {
        margin-top: -85px;
        }
        #register-link{
            padding: 50px;
            float: right;
            text-decoration: none;
        }
    </style>
{% endblock %}

templates/accounts/password_change.html
{% extends 'accounts/base.html' %}

{% block body %}
<form method='POST'>
    {% if form.errors %}
        <p>Check old password</p>
    {% endif %}
    {{form.old_password}}
    {{form.new_password1}}
    {{form.new_password2}}
    <input type="submit" value='Change'>
    {% csrf_token %}
</form>

{% endblock %}

templates/accounts/register.html
{% extends 'contests/base.html' %}
{% block title %} Register {% endblock %}

{% block body %}
    <div class="container">
        {% if messages %}
            <div class=''>
                {% for message in messages %}
                    <div class='notification {{message.tags}}' id='disappear'>
                        <p>{{message|safe}} <span class='float-right ' onclick='disappear()'><i class='fas fa-times'></i></span></p>     
                    </div>
                {% endfor %}
            </div>         
        {% endif %}

        <div id="login">
            <div class="container">
                <div id="login-row" class="row justify-content-center align-items-center">
                    <div id="login-column" class="col-md-6">
                        <div id="login-box" class="col-md-12">
                            <form id="login-form" class="form" action="" method="post">
                                
                                <h3 class="text-center text-info">Register</h3>
                                <div class="form-group">
                                    <label for="username" class="text-info">Name:</label><br>
                                    
                                        {{ user_form.name }}
                                    
                                </div>
                                <div class="form-group">
                                    <label for="email" class="text-info">Email:</label><br>
                                    
                                        {{ user_form.email }}
                                    
                                </div>
                                <div class="form-group">
                                    <label for="password" class="text-info">Password:</label><br>
                                    
                                        {{ user_form.password}}
                                    
                                </div>
                                <div class="form-group">
                                    <label for="confirm-password" class="text-info">Confirm Password:</label><br>
                                    
                                        {{ user_form.password_}}
                                    
                                </div>
                                <br />
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="submit" name="submit" class="btn btn-info btn-md" value="Join Now">
                                </div>
                                <div id="register-link" class="text-right">
                                    <p class="text-muted">Already have an account? <a href="{% url 'account:login' %}" class="text-info">Login</a></p>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--STYLE SHEET STARTS HERE -->
    <style>
        body {
            margin: 0;
            padding: 0;
            background: url('https://cdn.pixabay.com/photo/2014/07/01/12/35/observation-deck-381232_960_720.jpg');
            height: 105vh;
        }
        #login .container #login-row #login-column #login-box {
        margin-top: 120px;
        max-width: 500px;
        height: 500px;
        border: 1px solid #9C9C9C;
        background-color: #EAEAEA;
        }
        #login .container #login-row #login-column #login-box #login-form {
        padding: 20px;
        }
        #login .container #login-row #login-column #login-box #login-form #register-link {
        margin-top: -85px;
        }
        #register-link{
            padding: 40px;
            float: right;
            text-decoration: none;
            margin-left: 40px;
        }
    </style>
{% endblock %}